[package]
name = "tide"
version = "0.3.0"
description = "Serve the web – HTTP server framework"
authors = [
    "Aaron Turon <aturon@mozilla.com>",
    "Yoshua Wuyts <yoshuawuyts@gmail.com>",
]
documentation = "https://docs.rs/tide"
keywords = ["tide", "http", "web", "framework", "async"]
categories = [
  "network-programming",
  "asynchronous",
  "web-programming::http-server"
]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/http-rs/tide"

[features]
default = ["hyper"]
hyper = ["http-service-hyper"]
unstable = []

[dependencies]
accept-encoding = "0.2.0-alpha.2"
async-compression = "0.1.0-alpha.7"
cookie = { version = "0.12.0", features = ["percent-encode"] }
http = "0.1.19"
http-service = "0.3.1"
http-service-hyper = { version = "0.3.1", optional = true }
log = "0.4.8"
# multipart = { version = "0.16.1", features = ["server"] }
route-recognizer = "0.1.13"
serde = "1.0.102"
serde_json = "1.0.41"
serde_qs = "0.5.0"
async-std = "0.99.11"

[dev-dependencies]
basic-cookies = "0.1.3"
bytes = "0.4.12"
futures-fs = "0.0.5"
futures-util-preview = { version = "0.3.0-alpha.19", features = ["compat"] }
http-service-mock = "0.3.1"
juniper = "0.14.1"
mime = "0.3.14"
mime_guess = "2.0.1"
percent-encoding = "2.1.0"
serde = { version = "1.0.102", features = ["derive"] }
structopt = "0.3.3"
